### ISSUE TITLE
feature-request [Annotations]

### ISSUE THREAD

**Issue by YNNS** [rethinkdb/rethinkdb-java#1]
Hey there,
it would be great if there would be annotations like `@Ignored` and `@DatabaseName("dbName")`

**Comment by thelinuxlich** [comment]
Right now the Java driver doesn't have a official mantainer

**Comment by NotJustAnna** [comment]
All Jackson annotations are supported in 2.4.0 driver, which will be released soon. `@DatabaseName` doesn't make a ton of sense, IMHO. Once 2.4.0 driver is released, learn how to use Jackson annotations and you're good to go.
