### ISSUE TITLE
Enum serialization/deserialization support

### ISSUE THREAD

**Issue by YNNS** [rethinkdb/rethinkdb-java#2]
If I deserialize an object from database which has an enum attribute with constructor the deserilization fails.

**Comment by thelinuxlich** [comment]
Right now the Java driver doesn't have a official mantainer

**Comment by NotJustAnna** [comment]
Reproduced in 2.4.0 driver.
Fix shouldn't be hard, it's a change in `com.rethinkdb.net.Util#convertToPojo`, essentially.
